# Generated by Django 4.1.2 on 2022-10-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flexpage',
            options={'verbose_name': 'Page divers', 'verbose_name_plural': 'Pages divers'},
        ),
        migrations.AddField(
            model_name='flexpage',
            name='text',
            field=models.TextField(blank=True, default='Consectetur modi sit neque etincidunt labore non magnam. Quaerat numquam quiquia dolorem dolorem neque velit. Sed eius porro non. Est porro neque tempora labore dolore. Magnam amet ut magnam consectetur. Numquam eius consectetur dolorem eius dolore. Dolorem est magnam neque est. Neque etincidunt non est dolor. Voluptatem modi sit voluptatem quaerat sit.', max_length=600, null=True),
        ),
    ]
